export const NAMESPACE = "chauffage.systeme";

export const RULES = {
	consommations: "consommations",
	bch: "bch",
	cch: "cch",
	cch_elec: "cch_elec",
	cch_enr: "cch_enr",
	cch1: "cch1",
	cch2: "cch2",
	caux_dist: "caux_dist",
	caux_dist_enr: "caux_dist_enr",
	rdim: "rdim",
	role: "role",
	pch: "pch",
	pe: "pe",
	t: "t",
	dht: "dht",
	int: "int",
	ich: "ich",
	rd: "rd",
	re: "re",
	rg: "rg",
	rr: "rr",
	pcircem: "pcircem",
	temperature_distribution: "temperature_distribution",
	isolation_reseau: "isolation_reseau",
} as const;
