export const NAMESPACE = "ecs.generateur";

export const RULES = {
	consommations: "consommations",
	cecs: "cecs",
	cecs_elec: "cecs_elec",
	caux_gen: "caux_gen",
	caux_gen_enr: "caux_gen_enr",
	rdim: "rdim",
	pn: "pn",
	pdim: "pdim",
	pecs: "pecs",
	paux: "paux",
	cop: "cop",
	combustion: "combustion",
	cr: "cr",
	qgw: "qgw",
	qgen: "qgen",
	type_generateur: "type_generateur",
	energie_generateur: "energie_generateur",
	mode_combustion: "mode_combustion",
	presence_ventouse: "presence_ventouse",
	annee_installation: "annee_installation",
	volume_stockage: "volume_stockage",
} as const;
