export const NAMESPACE = "enveloppe";

export const RULES = {
	gv: "gv",
	ubat: "ubat",
	dp: "dp",
	dp_murs: "dp_murs",
	dp_planchers_bas: "dp_planchers_bas",
	dp_planchers_hauts: "dp_planchers_hauts",
	dp_baies: "dp_baies",
	dp_portes: "dp_portes",
	pt: "pt",
	dr: "dr",
	sdep: "sdep",
	sdep_murs: "sdep_murs",
	sdep_planchers_bas: "sdep_planchers_bas",
	sdep_planchers_hauts: "sdep_planchers_hauts",
	sdep_baies: "sdep_baies",
	sdep_portes: "sdep_portes",
	inertie: "inertie",
	hperm: "hperm",
	qvinf: "qvinf",
	n50: "n50",
	q4pa: "q4pa",
	q4paenv: "q4paenv",
	q4paconv: "q4paconv",
	isolation_murs_plafonds: "isolation_murs_plafonds",
	presence_joints: "presence_joints",
	isolation_planchers_hauts: "isolation_planchers_hauts",
	presence_protection_solaire: "presence_protection_solaire",
	logement_traversant: "logement_traversant",
	parois_anciennes: "parois_anciennes",
	sse: "sse",
} as const;
