export const NAMESPACE = "chauffage.generateur";

export const RULES = {
	consommations: "consommations",
	cch: "cch",
	cch_elec: "cch_elec",
	caux_gen: "caux_gen",
	caux_gen_enr: "caux_gen_enr",
	rdim: "rdim",
	pn: "pn",
	pdim: "pdim",
	pch: "pch",
	paux: "paux",
	combustion: "combustion",
	scop: "scop",
	tfonc30: "tfonc30",
	tfonc100: "tfonc100",
	qgen_rec: "qgen_rec",
	qgen: "qgen",
	type_generateur: "type_generateur",
	energie_generateur: "energie_generateur",
	mode_combustion: "mode_combustion",
	presence_ventouse: "presence_ventouse",
	presence_regulation: "presence_regulation",
	annee_installation: "annee_installation",
} as const;
