production.ppv:
  id: production.ppv
  description: Production d'électricité photovoltaique
  type: number
  unite: kWh/an
  dependances:
    - production.panneau_photovoltaique.ppv

production.celec_ac:
  id: production.celec_ac
  description: Électricité photovoltaïque autoconsommée
  type: number
  unite: kWh/an
  dependances:
    - production.ppv
    - production.celec
    - production.tapl

production.celec_ac_ch:
  id: production.celec_ac_ch
  description: Électricité photovoltaïque autoconsommée pour le chauffage
  type: number
  unite: kWh/an
  dependances:
    - production.celec
    - production.celec_ac
    - production.tapl
    - production.celec_ch

production.celec_ac_ecs:
  id: production.celec_ac_ecs
  description: Électricité photovoltaïque autoconsommée pour l'eau chaude sanitaire
  type: number
  unite: kWh/an
  dependances:
    - production.celec
    - production.celec_ac
    - production.tapl
    - production.celec_ecs

production.celec_ac_fr:
  id: production.celec_ac_fr
  description: Électricité photovoltaïque autoconsommée pour le refroidissement
  type: number
  unite: kWh/an
  dependances:
    - production.celec
    - production.celec_ac
    - production.tapl
    - production.celec_fr

production.celec_ac_ecl:
  id: production.celec_ac_ecl
  description: Électricité photovoltaïque autoconsommée pour l'éclairage
  type: number
  unite: kWh/an
  dependances:
    - production.celec
    - production.celec_ac
    - production.tapl
    - production.celec_ecl

production.celec_ac_aux_dist:
  id: production.celec_ac_aux_dist
  description: Électricité photovoltaïque autoconsommée pour les auxiliaires de distribution
  type: number
  unite: kWh/an
  dependances:
    - production.celec
    - production.celec_ac
    - production.tapl
    - production.celec_aux_dist

production.celec_ac_aux_vent:
  id: production.celec_ac_aux_vent
  description: Électricité photovoltaïque autoconsommée pour les auxiliaires de ventilation
  type: number
  unite: kWh/an
  dependances:
    - production.celec
    - production.celec_ac
    - production.tapl
    - production.celec_aux_vent

production.celec_ac_autres:
  id: production.celec_ac_autres
  description: Électricité photovoltaïque autoconsommée pour les autres usages
  type: number
  unite: kWh/an
  dependances:
    - production.celec
    - production.celec_ac
    - production.tapl
    - production.celec_autres

production.celec:
  id: production.celec
  description: Consommation d'électricité totale
  type: number
  unite: kWh/an
  dependances:
    - production.celec_ch
    - production.celec_ecs
    - production.celec_fr
    - production.celec_ecl
    - production.celec_aux_dist
    - production.celec_aux_vent
    - production.celec_autres

production.tapl:
  id: production.tapl
  description: Coefficient de calage représentant le taux d'auto-production maximum pouvant être atteint lorsque la production d'électricité renouvelable augmente
  type: number
  dependances:
    - production.celec_ch
    - production.celec_ecs
    - production.celec_fr
    - production.celec_ecl
    - production.celec_aux_dist
    - production.celec_aux_vent
    - production.celec_autres

production.celec_ch:
  id: production.celec_ch
  description: Consommation d'électricité pour le chauffage
  type: number
  unite: kWh/an
  dependances:
    - chauffage.cch_elec
    - chauffage.caux_gen

production.celec_ecs:
  id: production.celec_ecs
  description: Consommation d'électricité pour l'eau chaude sanitaire
  type: number
  unite: kWh/an
  dependances:
    - ecs.cecs_elec
    - ecs.caux_gen

production.celec_fr:
  id: production.celec_fr
  description: Consommation d'électricité pour le refroidissement
  type: number
  unite: kWh/an
  dependances:
    - refroidissement.cfr_elec

production.celec_ecl:
  id: production.celec_ecl
  description: Consommation d'électricité pour l'éclairage
  type: number
  unite: kWh/an
  dependances:
    - eclairage.cecl

production.celec_aux_dist:
  id: production.celec_aux_dist
  description: Consommation d'électricité pour les auxiliaires de distribution
  type: number
  unite: kWh/an
  dependances:
    - chauffage.caux_dist
    - ecs.caux_dist

production.celec_aux_vent:
  id: production.celec_aux_vent
  description: Consommation d'électricité pour les auxiliaires de ventilation
  type: number
  unite: kWh/an
  dependances:
    - ventilation.caux

production.celec_autres:
  id: production.celec_autres
  description: Consommations d'électricité pour les autres usages
  type: number
  unite: kWh/an
  dependances:
    - batiment.sh

production.panneau_photovoltaique.ppv:
  id: production.panneau_photovoltaique.ppv
  description: Production d'électricité du panneau photovoltaïque
  type: number
  unite: kWh/mois
  dependances:
    - climat.epv
    - production.panneau_photovoltaique.kpv

production.panneau_photovoltaique.kpv:
  id: production.panneau_photovoltaique.kpv
  description: Coefficient de pondération prenant en compte l'altération par rapport à l'orientation optimale du panneau photovoltaïque
  type: number
