import { describe, it, expect } from "vitest";
import * as models from "@open-dpe-logement/models";
import { createContext, services } from "../../src/index.js";

const DIAGNOSTIC = {
	id: "019a7391-cd73-7c54-b29a-4795ec32a2fc",
	date_visite: "2021-10-07",
	date_etablissement: "2021-10-09",
	type: "batiment",
	batiment: {
		rnb_id: null,
		type: "maison",
		annee_construction: 1936,
		annee_renovation: null,
		altitude: 200,
		logements: 1,
		surface_habitable: 82,
		hauteur_sous_plafond: 2.5,
		materiaux_anciens: false,
		appartements_visites: [],
		logement: null,
		adresse: {
			nom: "11 Rue de Belleville 08400 Toges",
			code_postal: "08400",
			code_insee: "08453",
			commune: "Toges",
			ban_id: "08453_0008_00011",
		},
	},
	enveloppe: {
		exposition: "simple",
		q4pa_conv: null,
		presence_brasseurs_air: false,
		niveaux: [
			{
				id: "019a7391-cc18-7a22-ba5d-4aba7a70e165",
				description: "Niveau reconstitué",
				surface: 82,
				inertie_paroi_verticale: "legere",
				inertie_plancher_bas: "legere",
				inertie_plancher_haut: "legere",
			},
		],
		locaux_non_chauffes: [
			{
				id: "019a7391-cc12-706e-b2c2-cb1075f75b85",
				description: "Cellier",
				type: "cellier",
				parois: [
					{
						id: "019a7391-cc13-7fa7-aed0-42f5562e1577",
						description: "Paroi",
						isolation: false,
						position: {
							surface: 7.1,
							mitoyennete: "exterieur",
						},
					},
				],
				baies: [],
			},
			{
				id: "019a7391-cc14-7aeb-9233-d81db5bda49f",
				description: "Local non chauffé reconstitué",
				type: "comble_faiblement_ventile",
				parois: [
					{
						id: "019a7391-cc14-7aeb-9233-d81db5e2fd57",
						description: "Paroi reconstituée",
						isolation: false,
						position: {
							surface: 57.4,
							mitoyennete: "exterieur",
						},
					},
				],
				baies: [],
			},
		],
		baies: [
			{
				id: "019a7391-cc0c-7912-b61e-a9aa65299243",
				description: "Fenêtre 1",
				type: "fenetre_battante",
				presence_protection_solaire: false,
				type_fermeture: "volets_roulants_pvc_bois_epaisseur_lte_12mm",
				annee_installation: null,
				ug: null,
				uw: null,
				ujn: null,
				sw: null,
				position: {
					surface: 5,
					mitoyennete: "exterieur",
					type_pose: "nu_interieur",
					inclinaison: 90,
					orientation: "nord",
					paroi_id: "019a7391-cc0e-7dcc-b274-32fdbec4c44b",
					local_non_chauffe_id: null,
					baie_id: null,
					masques: [],
				},
				vitrage: {
					type: "simple_vitrage",
					nature_lame: null,
					epaisseur_lame: null,
				},
				survitrage: {
					type: "survitrage_simple",
					epaisseur_lame: 6,
				},
				menuiserie: {
					materiau: null,
					largeur_dormant: 50,
					presence_soubassement: false,
					presence_joint: false,
					presence_retour_isolation: false,
					presence_rupteur_pont_thermique: false,
				},
			},
			{
				id: "019a7391-cc10-77e8-8534-dba4d8a49b64",
				description: "Fenêtre 2",
				type: "fenetre_battante",
				presence_protection_solaire: false,
				type_fermeture: "volets_roulants_pvc_bois_epaisseur_lte_12mm",
				annee_installation: null,
				ug: null,
				uw: null,
				ujn: null,
				sw: null,
				position: {
					surface: 5,
					mitoyennete: "exterieur",
					type_pose: "nu_interieur",
					inclinaison: 90,
					orientation: "est",
					paroi_id: "019a7391-cc10-77e8-8534-dba4d8b87013",
					local_non_chauffe_id: null,
					baie_id: null,
					masques: [],
				},
				vitrage: {
					type: "double_vitrage",
					nature_lame: "air",
					epaisseur_lame: 16,
				},
				survitrage: null,
				menuiserie: {
					materiau: null,
					largeur_dormant: 50,
					presence_soubassement: false,
					presence_joint: false,
					presence_retour_isolation: false,
					presence_rupteur_pont_thermique: false,
				},
			},
			{
				id: "019a7391-cc10-77e8-8534-dba4d8fee6c5",
				description: "Fenêtre 3",
				type: "fenetre_battante",
				presence_protection_solaire: false,
				type_fermeture: "volets_roulants_pvc_bois_epaisseur_lte_12mm",
				annee_installation: null,
				ug: null,
				uw: null,
				ujn: null,
				sw: null,
				position: {
					surface: 5,
					mitoyennete: "exterieur",
					type_pose: "nu_interieur",
					inclinaison: 90,
					orientation: "sud",
					paroi_id: "019a7391-cc10-77e8-8534-dba4d94f4e94",
					local_non_chauffe_id: null,
					baie_id: null,
					masques: [],
				},
				vitrage: {
					type: "simple_vitrage",
					nature_lame: null,
					epaisseur_lame: null,
				},
				survitrage: {
					type: "survitrage_simple",
					epaisseur_lame: 6,
				},
				menuiserie: {
					materiau: null,
					largeur_dormant: 50,
					presence_soubassement: false,
					presence_joint: false,
					presence_retour_isolation: false,
					presence_rupteur_pont_thermique: false,
				},
			},
			{
				id: "019a7391-cc10-77e8-8534-dba4d9d1771b",
				description: "Fenêtre 4",
				type: "fenetre_battante",
				presence_protection_solaire: false,
				type_fermeture: "volets_roulants_pvc_bois_epaisseur_lte_12mm",
				annee_installation: null,
				ug: null,
				uw: null,
				ujn: null,
				sw: null,
				position: {
					surface: 5,
					mitoyennete: "exterieur",
					type_pose: "nu_interieur",
					inclinaison: 90,
					orientation: "ouest",
					paroi_id: "019a7391-cc10-77e8-8534-dba4da38845f",
					local_non_chauffe_id: null,
					baie_id: null,
					masques: [],
				},
				vitrage: {
					type: "simple_vitrage",
					nature_lame: null,
					epaisseur_lame: null,
				},
				survitrage: {
					type: "survitrage_simple",
					epaisseur_lame: 6,
				},
				menuiserie: {
					materiau: null,
					largeur_dormant: 50,
					presence_soubassement: false,
					presence_joint: false,
					presence_retour_isolation: false,
					presence_rupteur_pont_thermique: false,
				},
			},
		],
		murs: [
			{
				id: "019a7391-cc0e-7dcc-b274-32fdbec4c44b",
				description: "Mur 1",
				structures: [
					{
						materiau: "beton_cellulaire",
						epaisseur: 15,
						materiau_ancien: false,
					},
				],
				type_doublage: "sans_doublage",
				presence_enduit_isolant: false,
				inertie: null,
				annee_construction: null,
				annee_renovation: null,
				u0: null,
				u: null,
				position: {
					surface: 25,
					mitoyennete: "local_non_residentiel",
					local_non_chauffe_id: null,
				},
				isolation: {
					etat: true,
					type: "itr",
					annee_installation: null,
					epaisseur: null,
					resistance_thermique: null,
				},
			},
			{
				id: "019a7391-cc10-77e8-8534-dba4d8b87013",
				description: "Mur 2",
				structures: [
					{
						materiau: "brique_pleine_simple",
						epaisseur: 34,
						materiau_ancien: false,
					},
				],
				type_doublage: "sans_doublage",
				presence_enduit_isolant: false,
				inertie: null,
				annee_construction: null,
				annee_renovation: null,
				u0: null,
				u: null,
				position: {
					surface: 25,
					mitoyennete: "local_non_residentiel",
					local_non_chauffe_id: null,
				},
				isolation: {
					etat: false,
					type: null,
					annee_installation: null,
					epaisseur: null,
					resistance_thermique: null,
				},
			},
			{
				id: "019a7391-cc10-77e8-8534-dba4d94f4e94",
				description: "Mur 3",
				structures: [
					{
						materiau: "brique_pleine_simple",
						epaisseur: 25,
						materiau_ancien: false,
					},
				],
				type_doublage: "sans_doublage",
				presence_enduit_isolant: false,
				inertie: null,
				annee_construction: null,
				annee_renovation: null,
				u0: null,
				u: null,
				position: {
					surface: 25,
					mitoyennete: "exterieur",
					local_non_chauffe_id: null,
				},
				isolation: {
					etat: true,
					type: "itr",
					annee_installation: null,
					epaisseur: null,
					resistance_thermique: null,
				},
			},
			{
				id: "019a7391-cc12-706e-b2c2-cb1075f75b85",
				description: "Mur 4",
				structures: [
					{
						materiau: "cloison_platre",
						epaisseur: null,
						materiau_ancien: false,
					},
				],
				type_doublage: "sans_doublage",
				presence_enduit_isolant: false,
				inertie: null,
				annee_construction: null,
				annee_renovation: null,
				u0: null,
				u: null,
				position: {
					surface: 25,
					mitoyennete: "local_non_chauffe",
					local_non_chauffe_id: "019a7391-cc12-706e-b2c2-cb1075f75b85",
				},
				isolation: {
					etat: false,
					type: null,
					annee_installation: null,
					epaisseur: null,
					resistance_thermique: null,
				},
			},
		],
		planchers_bas: [
			{
				id: "019a7391-cc19-7bf7-ac11-fe321eac872c",
				description: "Plancher 1",
				type: "dalle_beton",
				inertie: null,
				annee_construction: null,
				annee_renovation: null,
				u0: null,
				u: null,
				position: {
					surface: 50,
					mitoyennete: "terre_plein",
					surface_ue: 50,
					perimetre_ue: 30,
					local_non_chauffe_id: null,
				},
				isolation: {
					etat: false,
					type: null,
					annee_installation: null,
					epaisseur: null,
					resistance_thermique: null,
				},
			},
		],
		planchers_hauts: [
			{
				id: "019a7391-cc14-7aeb-9233-d81db5bda49f",
				description: "Plafond 1",
				configuration: "plancher",
				type: "plafond_entre_solives_bois",
				inertie: null,
				annee_construction: null,
				annee_renovation: null,
				u0: null,
				u: null,
				position: {
					surface: 50,
					mitoyennete: "local_non_chauffe",
					local_non_chauffe_id: "019a7391-cc14-7aeb-9233-d81db5bda49f",
				},
				isolation: {
					etat: true,
					type: "iti",
					annee_installation: null,
					epaisseur: 200,
					resistance_thermique: null,
				},
			},
		],
		portes: [
			{
				id: "019a7391-cc1c-7be5-b823-e52691b20cfd",
				description: "Porte 1",
				isolation: false,
				materiau: "bois",
				annee_installation: null,
				u: null,
				position: {
					type_pose: "nu_interieur",
					surface: 3,
					mitoyennete: "exterieur",
					presence_sas: false,
					paroi_id: "019a7391-cc0e-7dcc-b274-32fdbec4c44b",
					local_non_chauffe_id: null,
				},
				menuiserie: {
					largeur_dormant: 50,
					presence_joint: false,
					presence_retour_isolation: null,
				},
				vitrage: {
					surface: 1.5,
					type: "simple_vitrage",
				},
			},
			{
				id: "019a7391-cc1c-7be5-b823-e52692b27eff",
				description: "Porte 2",
				isolation: false,
				materiau: "pvc",
				annee_installation: null,
				u: null,
				position: {
					type_pose: "nu_interieur",
					surface: 3,
					mitoyennete: "exterieur",
					presence_sas: false,
					paroi_id: "019a7391-cc10-77e8-8534-dba4d8b87013",
					local_non_chauffe_id: null,
				},
				menuiserie: {
					largeur_dormant: 50,
					presence_joint: false,
					presence_retour_isolation: null,
				},
				vitrage: {
					surface: 0.66,
					type: "double_vitrage",
				},
			},
		],
		ponts_thermiques: [
			{
				id: "019a7391-cc1b-79c3-8eb4-6b4bbb2f9c64",
				description: "Plancher 1-Mur 1",
				longueur: 2,
				kpt: null,
				liaison: {
					type: "plancher_bas_mur",
					pont_thermique_partiel: false,
					mur_id: "019a7391-cc0e-7dcc-b274-32fdbec4c44b",
					plancher_id: "019a7391-cc19-7bf7-ac11-fe321eac872c",
					ouverture_id: null,
				},
			},
			{
				id: "019a7391-cc1c-7be5-b823-e5268c179bb6",
				description: "Plancher 1-Mur 2",
				longueur: 2.3,
				kpt: null,
				liaison: {
					type: "plancher_bas_mur",
					pont_thermique_partiel: false,
					mur_id: "019a7391-cc10-77e8-8534-dba4d8b87013",
					plancher_id: "019a7391-cc19-7bf7-ac11-fe321eac872c",
					ouverture_id: null,
				},
			},
			{
				id: "019a7391-cc1c-7be5-b823-e5268c1c903b",
				description: "Plancher 1-Mur 3",
				longueur: 2.7,
				kpt: null,
				liaison: {
					type: "plancher_bas_mur",
					pont_thermique_partiel: false,
					mur_id: "019a7391-cc10-77e8-8534-dba4d94f4e94",
					plancher_id: "019a7391-cc19-7bf7-ac11-fe321eac872c",
					ouverture_id: null,
				},
			},
			{
				id: "019a7391-cc1c-7be5-b823-e5268d01d9b3",
				description: "Plancher 1-Mur 4",
				longueur: 3,
				kpt: null,
				liaison: {
					type: "plancher_bas_mur",
					pont_thermique_partiel: false,
					mur_id: "019a7391-cc12-706e-b2c2-cb1075f75b85",
					plancher_id: "019a7391-cc19-7bf7-ac11-fe321eac872c",
					ouverture_id: null,
				},
			},
			{
				id: "019a7391-cc1c-7be5-b823-e526904c6acf",
				description: "Fenêtre 1 - Mur 1",
				longueur: 6,
				kpt: null,
				liaison: {
					type: "baie_mur",
					pont_thermique_partiel: false,
					mur_id: "019a7391-cc0e-7dcc-b274-32fdbec4c44b",
					plancher_id: null,
					ouverture_id: "019a7391-cc0c-7912-b61e-a9aa65299243",
				},
			},
			{
				id: "019a7391-cc1c-7be5-b823-e526909c61fa",
				description: "Fenêtre 2 - Mur 2",
				longueur: 6.6,
				kpt: null,
				liaison: {
					type: "baie_mur",
					pont_thermique_partiel: false,
					mur_id: "019a7391-cc10-77e8-8534-dba4d8b87013",
					plancher_id: null,
					ouverture_id: "019a7391-cc10-77e8-8534-dba4d8a49b64",
				},
			},
			{
				id: "019a7391-cc1c-7be5-b823-e52691a7246c",
				description: "Porte 1-Mur 1",
				longueur: 4.7,
				kpt: null,
				liaison: {
					type: "porte_mur",
					pont_thermique_partiel: false,
					mur_id: "019a7391-cc0e-7dcc-b274-32fdbec4c44b",
					plancher_id: null,
					ouverture_id: "019a7391-cc1c-7be5-b823-e52691b20cfd",
				},
			},
			{
				id: "019a7391-cc1c-7be5-b823-e52691bcf837",
				description: "Porte 2-Mur 2",
				longueur: 4.2,
				kpt: null,
				liaison: {
					type: "porte_mur",
					pont_thermique_partiel: false,
					mur_id: "019a7391-cc10-77e8-8534-dba4d8b87013",
					plancher_id: null,
					ouverture_id: "019a7391-cc1c-7be5-b823-e52692b27eff",
				},
			},
		],
	},
	chauffage: {
		emetteurs: [],
		generateurs: [
			{
				id: "019a7391-cc22-775c-b6cb-ce8df9a638df",
				description: "Radiateur électrique NFC",
				type: "convecteur_electrique",
				energie: "electricite",
				bienergie: null,
				annee_installation: null,
				position: {
					cascade: null,
					generateur_collectif: false,
					generateur_multi_batiment: false,
					position_volume_chauffe: true,
					position_chaudiere: null,
					generateur_mixte_id: null,
					reseau_chaleur_id: null,
				},
				signaletique: {
					pn: null,
					label: "nf_performance",
					scop: null,
					mode_combustion: null,
					presence_ventouse: null,
					presence_regulation: null,
					pveilleuse: null,
					qp0: null,
					rpn: null,
					rpint: null,
					tfonc30: null,
					tfonc100: null,
				},
			},
		],
		installations: [
			{
				id: "019a7391-cc20-7ae3-a6ba-4c2b8c7f5134",
				description: "Chauffage sans solaire",
				surface: 100,
				type: "divise",
				installation_collective: false,
				comptage_individuel: null,
				regulation_terminale: null,
				programmation: "terminal_avec_minimum_temperature",
				solaire_thermique: null,
				systemes: [
					{
						id: "019a7391-cc22-775c-b6cb-ce8df9a638df",
						description: "Radiateur électrique NFC",
						generateur_id: "019a7391-cc22-775c-b6cb-ce8df9a638df",
						type: "divise",
						reseau: null,
					},
				],
			},
		],
	},
	ecs: {
		generateurs: [
			{
				id: "019a7391-cc27-70c1-901c-b1ee00db4d21",
				description: "Chauffe-eau vertical",
				type: "chauffe_eau",
				energie: "electricite",
				bienergie: null,
				annee_installation: null,
				position: {
					generateur_collectif: false,
					generateur_multi_batiment: false,
					position_volume_chauffe: true,
					position_chauffe_eau: "chauffe_eau_vertical",
					generateur_mixte_id: null,
					reseau_chaleur_id: null,
				},
				stockage: {
					type: "integre",
					volume: 200,
					position_volume_chauffe: true,
				},
				signaletique: {
					pn: null,
					label: null,
					cop: null,
					mode_combustion: null,
					presence_ventouse: null,
					pveilleuse: null,
					qp0: null,
					rpn: null,
				},
			},
		],
		installations: [
			{
				id: "019a7391-cc26-79b2-96ba-003e5ef593af",
				description: "Chauffe-eau vertical",
				surface: 100,
				installation_collective: false,
				solaire_thermique: null,
				systemes: [
					{
						id: "019a7391-cc27-70c1-901c-b1ee00db4d21",
						description: "Chauffe-eau vertical",
						generateur_id: "019a7391-cc27-70c1-901c-b1ee00db4d21",
						reseau: {
							alimentation_contigue: false,
							niveaux_desservis: 2,
							isolation: null,
							bouclage: "non_boucle",
						},
					},
				],
			},
		],
	},
	refroidissement: {
		generateurs: [
			{
				id: "019a7391-cc2b-7c3e-9f5c-0d4e8f9b6c3a",
				description: "Climatiseur",
				type: "autre",
				energie: "electricite",
				annee_installation: null,
				seer: null,
				reseau_froid_id: null,
			},
		],
		installations: [
			{
				id: "019a7391-cc2e-71cc-9a54-ac53c1f7b046",
				description: "Installation principale",
				surface: 50,
				generateurs: ["019a7391-cc2b-7c3e-9f5c-0d4e8f9b6c3a"],
			},
		],
	},
	ventilation: {
		installations: [
			{
				id: "019a7391-cc2e-71cc-9a54-ac53c1f7b046",
				description: "Installation principale",
				surface: 100,
				type: "ventilation_ouverture_fenetres",
				installation_collective: null,
				presence_echangeur_thermique: null,
				annee_installation: null,
			},
		],
	},
	production: {
		panneaux_photovoltaiques: [
			{
				id: "019a7391-cc31-71c3-9584-d54f4a18eb28",
				description: "Panneau photovoltaïque",
				orientation: "sud_est",
				inclinaison: 30,
				modules: 1,
				surface: 10,
				installation_collective: false,
			},
		],
	},
} as unknown as models.diagnostic.Diagnostic;

describe("Rules", () => {
	it("aucun cycle détecté", () => {
		const context = createContext(DIAGNOSTIC);

		try {
			const data = services.diagnostic.calcule(context);
			expect(data).toHaveProperty("data");
		} catch (error) {
			console.error(error);
		}
		console.log(JSON.stringify(Object.fromEntries(context.log())));
	});
});
