import { runTests } from "./utils.js";
import * as formulas from "../../src/rules/chauffage/systeme/formulas.js";

runTests("chauffage.systeme.test.yaml", {
	consommations: formulas.calcule_consommations,
	rg_combustion: formulas.calcule_rg_combustion,
	rg_pac: formulas.calcule_rg_pac,
	rg_reseau_chaleur: formulas.calcule_rg_reseau_chaleur,
	rg_autres: formulas.calcule_rg_autres,
	rd: formulas.calcule_rd,
	re: formulas.calcule_re,
	rr: formulas.calcule_rr,
	cch: formulas.calcule_cch,
	cch1: formulas.calcule_cch1,
	cch2: formulas.calcule_cch2,
	cch_elec: formulas.calcule_cch_elec,
	cch_enr: formulas.calcule_cch_enr,
	caux_dist: formulas.calcule_caux_dist,
	caux_dist_enr: formulas.calcule_caux_dist_enr,
	int: formulas.calcule_int,
	ich: formulas.calcule_ich,
	bch: formulas.calcule_bch,
	pch: formulas.calcule_pch,
	pe: formulas.calcule_pe,
	dht: formulas.calcule_dht,
	t: formulas.calcule_t,
	pcircem: formulas.calcule_pcircem,
	presence_circulateur_externe: formulas.set_presence_circulateur_externe,
	temperature_distribution: formulas.set_temperature_distribution,
	isolation_reseau: formulas.set_isolation_reseau,
});
